name: Check code style

on:
  - push

jobs:
  code-style:
    runs-on: ubuntu-latest

    name: Code style

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm dependencies
        run: npm clean-install

      - name: Check code style for PHP
        run: composer csPHP

      - name: Verify PSR-4 compliance of all PHP classes
        run: composer dump-autoload --strict-psr --no-scripts

      - name: Run static analysis for PHP
        run: composer stan

      - name: Check code style for CSS and JavaScript
        run: npm run cs
