name: Run tests

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2

    name: Tests PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm clean-install

      - name: Build
        run: npm run production

      - name: Run tests
        run: composer test
