name: Run tests and check code style

on: [push]

jobs:
    quality:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ 8.2, 8.1 ]

        name: ${{ matrix.os }} - PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install
              run: |
                  composer install --no-interaction
                  npm ci
                  npm run production

            - name: Code style checks for PHP
              run: composer cs

            - name: Code style checks for CSS and JavaScript
              run: npm run cs

            - name: Execute tests
              run: vendor/bin/phpunit
